service: preprocessing # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  region: eu-west-3
  iamRoleStatements:
   - Effect: "Allow"
     Action:
      - dynamodb:GetItem
     Resource: "arn:aws:dynamodb:eu-west-3:671560023774:table/CGU"

functions:
  preprocessing:
    handler: lambda_function.handler
    environment:
     NLTK_DATA: /var/task/nltk_data

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
   dockerizePip: true
