service: hilight-visualization # NOTE: update this with your service name
provider:
  name: aws
  runtime: python3.7
  region: eu-west-3

functions:
  hilight-visualisation:
    handler: lambda_function.handler
    environment:
     PLOTLY_DIR: /var/task/.plotly
    events:
      - http:
          path: /hilightvisu/{websitename}
          method: get
          cors: true
          integration: lambda
          request:
           parameters:
            paths:
             websitename: true
  hilight-global-chart:
    handler: lambda_function.handler2
    environment:
     PLOTLY_DIR: /var/task/.plotly
    events:
      - http:
          path: /hilightglobalchart
          method: get
          cors: true
          integration: lambda

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
   dockerizePip: true


