service: manage-db # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  region: eu-west-3
  timeout: 120
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource: "arn:aws:dynamodb:eu-west-3:671560023774:table/CGU" 

functions:
  manage-db:
    handler: lambda_function.handler
    events:
      - schedule: rate(24 hours)

custom:
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements
