service: manage-db # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  region: eu-west-3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:dynamodb:eu-west-3:671560023774:table/CGU" 

functions:
  hello:
    handler: handler.hello
    events:
      - schedule: rate(24 hours)

